title : jekyll-theme-slate
author :
  name : United Thru Action
  email : turnnyblue@gmail.com
  github : UnitedThruAction
  twitter : upcomingaction

# Tell Github to use the kramdown markdown interpreter
# (see https://help.github.com/articles/migrating-your-pages-site-from-maruku)
markdown: kramdown
